name: Generate Release

on:
  push:
    tags: ["*.*.*"]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build_packages:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release OpenEtw.CI.sln
      env:
        MINVER_VERSION: ${{ vars.MINVER_VERSION }}

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal OpenEtw.CI.sln

    - name: Pack
      run: dotnet pack -c Release OpenEtw.CI.sln

    - name: Push to NuGet
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}
      if: env.API_KEY != ''
      run: |
        dotnet nuget push
            build\Packages\Release\*.nupkg
            --source https://api.nuget.org/v3/index.json
            --api-key ${{ env.API_KEY }}

    - name: Publish EtwGen
      run: dotnet publish -c Release Tools\EtwGen\EtwGen.fsproj

    - name: Generate GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build\EtwGen\bin\Release\net472\publish\*

